<?php

return [
	'seo:autogen' => 'Autogenerate entity SEO',
	'seo:autogen:count' => 'SEO data has been autogenerated for %s of %s entities',
	'seo:edit' => 'Edit page SEO',
	'seo:path' => 'Original Path',
	'seo:sef_path' => 'SEF Path',
	'seo:sef_path:help' => 'Path without the domain with an opening forward slash, e.g. /file/sef-file-url',
	'seo:title' => 'Page Title',
	'seo:description' => 'Page Description',
	'seo:keywords' => 'Page Keywords',
	'seo:edit:success' => 'Page data has been saved successfully',
	'seo:edit:error' => 'Page data could not be saved',
];
